const LIST_MOVIE_REQUEST = "@listMovieReducer/LIST_MOVIE_REQUEST";
const LIST_MOVIE_SUCCESS = "@listMovieReducer/LIST_MOVIE_SUCCESS";
const LIST_MOVIE_FAILED = "@listMovieReducer/LIST_MOVIE_FAILED";

export { LIST_MOVIE_REQUEST, LIST_MOVIE_SUCCESS, LIST_MOVIE_FAILED };
