const DETAIL_MOVIE_REQUEST = "@detailMovieReducer/DETAIL_MOVIE_REQUEST";
const DETAIL_MOVIE_SUCCESS = "@detailMovieReducer/DETAIL_MOVIE_SUCCESS";
const DETAIL_MOVIE_FAILED = "@detailMovieReducer/DETAIL_MOVIE_FAILED";

export { DETAIL_MOVIE_FAILED, DETAIL_MOVIE_REQUEST, DETAIL_MOVIE_SUCCESS };
